# Generated by Django 5.2.8 on 2025-11-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='id',
            new_name='telegram_id',
        ),
        migrations.RenameField(
            model_name='botuser',
            old_name='name',
            new_name='username',
        ),
    ]
